CREATE TABLE accounts (
    -- // PRIMARY KEY = LET THE USER KNOW WHATS THE UNIQUE CALLED
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    pswd VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL ,
    comment_text TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    accounts_id INT NOT NULL,
    FOREIGN KEY (accounts_id) REFERENCES accounts (id) ON DELETE NO ACTION
    -- ON DELETE CASCADE
    -- ON DELETE SET NULL   

);